run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - gofumpt
    - goimports
    - errcheck
    - gosimple
    - unused
    - typecheck

linters-settings:
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
  revive:
    rules:
      - name: exported
        disabled: true
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/herdkey/hello-go

issues:
  exclude-use-default: false
  exclude-rules:
  max-same-issues: 50
  max-issues-per-linter: 50
