server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

logging:
  level: "info"
  format: "text"

telemetry:
  service_name: "hello-go"
  service_version: "1.0.0"
  enabled: true
