// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// EchoMessage defines model for EchoMessage.
type EchoMessage struct {
	// Author The author of the message
	Author string `json:"author"`

	// Message The message to echo
	Message string `json:"message"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// EchoJSONRequestBody defines body for Echo for application/json ContentType.
type EchoJSONRequestBody = EchoMessage
