// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	// Author The author of the message
	Author string `json:"author"`

	// Message The message to echo
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	// Author The author of the message
	Author *string `json:"author,omitempty"`

	// Message The echoed message
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// EchoJSONRequestBody defines body for Echo for application/json ContentType.
type EchoJSONRequestBody = EchoRequest
