import '../../.justfiles/go/base.just'

# Make local node binaries available like npm does
export PATH := "node_modules/.bin:" + env_var("PATH")

bootstrap:
    cdk bootstrap

build:
    tsc -p tsconfig.json

synth:
    cdk synth

deploy:
    cdk deploy

test:
    vitest

format:
    pnpm run format

lint:
    pnpm run lint
