name: hello-go-lambda

services:
  lambda:
    build:
      context: ../..
      dockerfile: docker/lambda/Dockerfile
      platforms:
        - linux/amd64
      # This is a new key
      # noinspection ComposeUnknownKeys
      provenance: false
      tags:
        - hello-go-lambda:latest
    ports:
      - "9000:8080"
    environment:
      - APP_LOGGING_LEVEL=info
      - APP_LOGGING_FORMAT=json
      - APP_TELEMETRY_ENABLED=true
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "./main"]
    restart: unless-stopped
    networks:
      - hello-go-lambda-network

networks:
  hello-go-lambda-network:
    driver: bridge
