name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: CI Setup
        run: just ci-setup

      - name: Run tests
        run: just test

      - name: Build
        run: just build

      - name: Lint
        run: just lint
