name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: CI Setup
        run: just ci-setup

      # Make sure the checked-in generated files are up to date
      # (generate is run as part of the CI setup step above)
      - name: Verify generate
        run: |
          git diff --name-only
          git diff --exit-code

      # Make sure go mod tidy has been run
      - name: Verify go.mod/go.sum tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Lint
        run: just lint

      - name: Run tests
        run: just test

      - name: Build
        run: just build
