name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: us-west-2
  INFRA_AWS_ACCOUNT_ID: "073835883885"

jobs:

  # Test and build the application
  # Upload the built binary as an artifact
  build:
    name: Build & Test
    uses: herdkey/github-actions/.github/workflows/go-build.yml@sav-6-common-go-actions
    with:
      build-artifact-name: &build_artifact_name hello-go-api
      build-output-file: ./bin/hello-go-api

  # Build and push the Docker image
  docker-build-push:
    name: Docker Build & Push
    uses: herdkey/github-actions/.github/workflows/docker-build-push.yml@sav-6-common-go-actions
    needs: build
    with:
      local-image-tag: 'hello-go-api:latest'
      component: api
      artifact-name: *build_artifact_name
      artifact-path: './bin'
    permissions:
      contents: read
      # Required by the AWS OIDC provider
      id-token: write
